fprintf('Name: Piratheipan Jeyakumar\n')
fprintf('Student #: 500696109\n')
fprintf('---------------------------------------------------------------------------------\n')
fprintf('Summary of Approach: \n')
fprintf('In my face detector I used a cell size of 6 and used a 6x6 feature\n')
fprintf('block on all the images at various different scales. Then I used the\n')
fprintf('SVM trained in part 1 to classify the images. To obtain the most\n')
fprintf('confident predictions I used a threshold of 0.98 for the confidences.\n') 
fprintf('After, I applied non maximum suppression (NMS) which is similar to the\n')
fprintf('code provided in evaluate_detections_on_test.m. I used a threshold of 1.0\n')
fprintf('to suppress any overlapping detections. I used another script called\n')
fprintf('detect_class_faces.m to plot bounding boxes on the faces in the class.jpg picture. \n')
fprintf('---------------------------------------------------------------------------------\n')

fprintf('Best Accuracy on Test Set: \n')
fprintf('The best accuracy I achieved was 0.572 and this was mainly due to\n')
fprintf('the false positives and our limited images in the training set.\n')
fprintf('---------------------------------------------------------------------------------\n')

fprintf('Performance Improvement: \n')
fprintf('I tried to improve the performance by adding other faces into the\n') 
fprintf('training dataset and tweaking the values of the threshold for the\n') 
fprintf('confidences and the number of recall values. \n')
fprintf('---------------------------------------------------------------------------------\n')

fprintf('Qualitative Evalutaion on Performance: \n')
fprintf('The performance on the class.jpg is good as it was able to detect \n')
fprintf('most of the faces. However, it was unable to detect some of the faces \n')
fprintf('as this is dues to the limited images in the training set. I had some \n')
fprintf('false positives where it detected some areas that are not faces. \n')
