fprintf('Name: Piratheipan Jeyakumar\n')
fprintf('Student #: 500696109\n')
fprintf('---------------------------------------------------------------------------------\n')
fprintf('Summary of Approach: \n')
fprintf('In part 1 of the face detector, I first generated a set of cropped, grayscale, \n')
fprintf('non-face images by randomly cropping the images into 36x36 crops which I will use\n') 
fprintf('as my negative training images. I generated the same number of negative images as \n')
fprintf('there is positive images. Then I obtained the HOG features for the positive and \n')
fprintf('negative training set using the VL toolbox. After, I split the training images into \n')
fprintf('80 percent training set and 20 percent validation set. Lastly, I trained the SVM on \n')
fprintf('the features from both the training set and the validation set. \n')
fprintf('---------------------------------------------------------------------------------\n')

fprintf('Best Accuracy on Test Set: \n')
fprintf('The best accuracy I achieved on the validation set is 0.995.\n')
fprintf('---------------------------------------------------------------------------------\n')

fprintf('Performance Improvement: \n')
fprintf('I improved the performance by decreasing the lambda value to 0.0001 \n')
fprintf('which gave me a better accuracy. \n')
fprintf('---------------------------------------------------------------------------------\n')